{
 "title": "TICK - Speedtest",
 "description": "Display the data collected using Telegraf and Speedtest CLI, stored in InfluxDB",
 "tags": [
  "Speedtest",
  "InfluxDb",
  "Telegraf",
  "ISP",
  "TICK"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "st_hosts",
    "label": "SpeedTest_Hosts",
    "query": "SHOW TAG VALUES ON \"speedtest\" FROM \"Speedtest\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "query": "SELECT last(\"download_bandwidth\")  / 131072 FROM \"Speedtest\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "download_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 131072" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "query": "SELECT last(\"download_bandwidth\")  / 131072 FROM \"Speedtest\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "download_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 131072" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "query": "SELECT last(\"upload_bandwidth\")  / 131072  FROM \"Speedtest\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "upload_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 131072 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "query": "SELECT last(\"upload_bandwidth\")  / 131072 FROM \"Speedtest\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "upload_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 131072" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "query": "SELECT last(\"ping_latency\") FROM \"Speedtest\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ping_latency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    }
   ]
  },
  {
   "title": "Ping Latency / Jitter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 3, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ping_latency\") FROM \"Speedtest\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Jitter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ping_jitter\") FROM \"Speedtest\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Jitter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "query": "SELECT last(\"ping_jitter\") FROM \"Speedtest\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ping_jitter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    }
   ]
  },
  {
   "title": "Tests Information",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 17 },
   "targets": [
    {
     "limit": 10,
     "measurement": "Speedtest",
     "query": "SELECT \"host\",\"server_id\", \"server_host\", \"server_ip\", \"server_location\", \"result_url\" FROM \"Speedtest\" WHERE $timeFilter ORDER BY time DESC LIMIT 3",
     "select": [
      [
       { "params": [ "server_id" ], "type": "field" }
      ],
      [
       { "params": [ "server_host" ], "type": "field" }
      ],
      [
       { "params": [ "server_ip" ], "type": "field" }
      ],
      [
       { "params": [ "server_location" ], "type": "field" }
      ],
      [
       { "params": [ "result_url" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    }
   ]
  }
 ]
}