{
 "title": "TICK - Speedtest",
 "description": "ISP quality monitoring using Telegraf + Speedtest CLI + InfluxDB 2.x",
 "tags": [
  "Speedtest",
  "InfluxDB",
  "Telegraf",
  "ISP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Speedtest\" and r._field == \"download_bandwidth\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value / 131072.0}))"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Speedtest\" and r._field == \"download_bandwidth\")\n  |> map(fn: (r) => ({r with _value: r._value / 131072.0}))\n  |> set(key: \"_field\", value: \"download\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Speedtest\" and r._field == \"upload_bandwidth\")\n  |> map(fn: (r) => ({r with _value: r._value / 131072.0}))\n  |> set(key: \"_field\", value: \"upload\")"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Speedtest\" and r._field == \"upload_bandwidth\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value / 131072.0}))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Speedtest\" and r._field == \"ping_latency\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Ping Latency / Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Speedtest\" and r._field == \"ping_latency\")\n  |> set(key: \"_field\", value: \"latency\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Speedtest\" and r._field == \"ping_jitter\")\n  |> set(key: \"_field\", value: \"jitter\")"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Speedtest\" and r._field == \"ping_jitter\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Tests Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Speedtest\")\n  |> filter(fn: (r) => r._field == \"server_host\" or r._field == \"server_ip\" or r._field == \"server_location\" or r._field == \"server_id\" or r._field == \"result_url\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 10)\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"host\", \"table\"])"
    }
   ]
  }
 ]
}