apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-telegraf
  labels:
    {{- include "speedtest-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/component: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: telegraf
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: telegraf
    spec:
      containers:
        - name: telegraf
          image: "{{ .Values.telegraf.image.repository }}:{{ .Values.telegraf.image.tag }}"
          imagePullPolicy: {{ .Values.telegraf.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-telegraf-config
